---

- name: Consumer Authentication Credentials | {{ outer_item.plugin|upper }}
  include: consumer_{{ outer_item.plugin }}_creds.yml
  with_items: "{{ kong_consumer_obj_auth_creds|default([]) }}"
  loop_control:
    loop_var: outer_item
