---

- name: Verify kong admin api available
  uri: 
    url: "{{ kong_admin_api_url|default('http://localhost:8001') }}"
  register: api_available
  until: api_available is succeeded
  retries: 60
  delay: 5

# Get list of consumer objects
- name: Get list of kong consumer objects
  uri:
    url: "{{ kong_admin_api_url }}/consumers"
  register: consumers
  until: consumers is succeeded
  retries: 10
  delay: 5

- debug: msg="{{ consumers.json }}"

# Move to README:
#
# In v0.13.0, significant changes were made to how kong entities are configured.
# For instance e.g. introduction of route and service object, and deprecation of
# api object.
# As a result this role has undergone significant refactoring.
# For the time being, this role supports both old and new config formats.
# To use the new config format set `kong_use_old_config_format` to `false`


- name: Set version of consumer tasks file to use
  set_fact:
    _format: "{% if kong_use_old_config_format %}deprecated/{% else %}{{ '' }}{% endif %}"

- set_fact: _cmd="add"

- set_fact: _cmd="delete"
  when: kong_delete_consumer_obj

- name: Kong Consumer Object Config
  include_tasks: "{{ _format }}consumer_{{ _cmd }}.yml"
