---

- name: Download kong package
  get_url: url="{{ kong_pkg_url }}" dest=/var/tmp validate_certs=no

- name: Install kong prerequisites
  apt: name="{{ item }}" update_cache=yes state=present
  with_items: "{{ kong_prereqs }}"

- name: Install kong
  apt: deb="/var/tmp/kong-{{ kong_version }}.{{ ansible_distribution_release }}_all.deb" state=present

- name: Create kong config file
  template: src=kong.yml.j2 dest="{{ kong_conf_dir }}/kong.yml" owner=root group=root mode=0644
  notify: Restart kong

- name: Ensure kong nginx working dir has appropriate permissions
  file: path="{{ kong_nginx_working_dir }}" owner=root group=root mode=0755

- name: Check kong running status
  shell: kong status || true
  register: run

- name: Start kong
  shell: kong start
  when: run.stdout.find('Kong is not running') != -1

# ToDo:
#   - consider running kong as non-root user
#   - consider writing a startup script for kong
