---
- name: Download and install postgresql gpg public signing key
  apt_key:
    url:   "{{ postgresql_apt_key_url }}"
    state: present
  when: ansible_os_family|lower == 'debian'

- name: Add postgresql apt repository definition to apt sources list
  apt_repository:
    repo: "{{ postgresql_apt_repo }}"
    update_cache: yes
    state:  present
  when: ansible_os_family|lower == 'debian'

- name: Add postgresql yum respository
  yum:
    name: "{{ postgresql_yum_repo_package }}"
    state: present
  when: ansible_os_family|lower == 'redhat'

- name: Install postgresql client package
  package:
    name: "{{ postgresql_client_package }}"
    state: present

- name: Deploy postgres helper script
  template:
    src: psql.sh.j2
    dest: /usr/local/bin/psql.sh
    mode: 0700
