---

##-------------------
##  v0.11.x
##-------------------

- name: Create kong config file | v0.10.x
  template: 
    src:  "0.11.x-kong.conf.j2"
    dest: "{{ kong_conf_dir }}/kong.conf"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Validate kong config
    - Restart kong

# "Reload kong" handler sometimes fails for instance when access_log config
# This is an edge case when custom log format is configured and name of log format
# appended to proxy_access_log property value ("logs/access.log"). Unfortunately,
# "kong reload" command does not recompile nginx-kong.conf as expected before
# reloading nginx. So the outdated nginx-kong.conf fails nginx config validation
# and nginx errors out.
# So it is safer to Restart
- name: Create kong custom nginx config file | v0.10.x or later
  template: 
    src:  custom-nginx.template.j2
    dest: "{{ kong_conf_dir }}/custom-nginx.template"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Validate kong config
    - Restart kong

- name: Check kong health status | v0.11.x or later
  shell: kong health || true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  register: health

- name: Set kong run status | v0.11.x or later
  set_fact: 
    run_status: down
  when: health.stderr.find('Kong is not running') != -1

- debug: var=health

- name: Update kong database schema | v0.11.x or earlier
  shell: >
      kong migrations up --conf {{ kong_conf_dir }}/kong.conf
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: run_status|default("up") == "down"
  run_once: true
  register: migration

- debug: var=migration.stdout_lines

- name: Start kong | v0.11.x or earlier
  shell: >
      ulimit -n "{{ kong_max_files_limit }}" && \
        kong start --conf {{ kong_conf_dir }}/kong.conf --nginx-conf {{ kong_conf_dir }}/custom-nginx.template
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: run_status|default("up") == "down"
  register: start

- debug: var=start.stdout_lines

#- pause: minutes=60
