---

- name: Set kong pkg download variables
  set_fact:
    kong_deb_pkg_url: "{{ kong_deb_pkg_url_pre_0_11_x }}"
    kong_rpm_pkg_url: "{{ kong_rpm_pkg_url_pre_0_11_x }}"
    kong_deb_pkg:     "kong-{{ kong_version }}.{{ ansible_distribution_release }}_all.deb"
    kong_rpm_pkg:     "kong-{{ kong_version }}.el7.noarch.rpm"
  when: kong_version|version_compare('0.11.0', '<')

# Debian
- name: Download kong deb package | Debian
  get_url:
    url: "{{ kong_deb_pkg_url }}"
    dest: "/var/tmp/{{ kong_deb_pkg }}"
    validate_certs: no
    force: no
  when: ansible_os_family|lower == 'debian'

- name: Install kong prerequisites (Debian/Ubuntu only)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ kong_prereqs }}"
  when: ansible_os_family|lower == 'debian'

- name: Install kong | Debian
  apt:
    deb:   "/var/tmp/{{ kong_deb_pkg }}"
    state: present
  when: ansible_os_family|lower == 'debian'

# RedHat
- name: Download kong rpm package | RedHat
  get_url: url="{{ kong_rpm_pkg_url }}" dest=/var/tmp validate_certs=no
  when: ansible_os_family|lower == 'redhat'

- name: Install kong | RedHat
  yum:
    name: "/var/tmp/{{ kong_rpm_pkg }}"
    disable_gpg_check: yes
    state: present
  when: ansible_os_family|lower == 'redhat'

- name: Create logrotate config for kong logs
  template:
    src:  logrotate.j2
    dest: /etc/logrotate.d/kong
    owner: root
    group: root
    mode: 0644

- name: Check for supported kong versions
  fail: msg="Kong {{ kong_version }} no longer supported"
  when: kong_version|version_compare('0.11.0', '<')

- name: Kong Server Config & Start
  include: "server-config.yml"
