---

- name: Validate kong config
  shell: >
      kong check {{ kong_conf_dir }}/kong.conf
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: kong_version|version_compare('0.9.0', '>=')

- name: Reload kong
  shell: >
      ulimit -n "{{ kong_max_files_limit }}" && \
        kong reload --conf {{ kong_conf_dir }}/kong.conf --nginx-conf {{ kong_conf_dir }}/custom-nginx.template
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: Restart kong | v0.8.x or earlier
  shell: ulimit -n "{{ kong_max_files_limit }}" && kong restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: Restart kong | v0.9.x or later
  shell: >
      ulimit -n "{{ kong_max_files_limit }}" && \
        kong restart --conf {{ kong_conf_dir }}/kong.conf --nginx-conf {{ kong_conf_dir }}/custom-nginx.template
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
